version: '3.1'

services:
  springboot:
    image: dockerhandsonimages/springbootmongo:2
    restart: always 
    container_name: springboot
    ports:
      - 8080:8080
    working_dir: /opt/app
    depends_on:
      - mongo 
    deploy:  
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure

  mongo:
    image: mongo
    container_name: springboot-mongo
    volumes:
      - mongodb:/data/db
    restart: always
    
volumes:
  mongodb:
    external: true
    
networks:
  springappnetwork:
    external: true
