apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: springapprs
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: springapp
  template:
    metadata:
      name: springapppod
      labels:
        app: springapp
    spec:
      containers:
      - name: springppcontainer
        image: dockerhandsonimages/springbootmongo:1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springappservice
spec:
  selector:
    app: springapp
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30100
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongodbrs
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: mongo
  template:
    metadata:
      name: mongopod
      labels:
        app: mongo
    spec:
      containers:
      - name: mongocontainer
        image: mongo
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongoservice
spec:
  selector:
    app: mongo
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
